### ISSUE TITLE
CoreML model?

### ISSUE THREAD

**Issue by schnabler** [CR-Ko/MegaDepth_Tensorflow#2]
Is there any chance you can provide CoreML exports so we can test it on mobile devices? Thanks.

**Comment by kkk324** [comment]
I need to overturn the trunks and boxes and little chance to find one. Even so, it is not the right way to do things. Because you will definitely need to adjust pre/post-processing to get all things right.

So my suggestion to you is to figure out the whole process of CoreML to convert tflite model to coreml model. 

It's simple.

**Comment by schnabler** [comment]
Yeah. I kind of tried it and failed, that's why I asked. "Simple" is obviously always a bit relative :). Thanks for your time though, appreciate your answer a lot.

**Comment by kkk324** [comment]
Maybe there is a version issue?
Thank to @supernlogn 's contribution.
He convert megadepth model from tf1 version to Keras version, as well as tf2 version.

Perhaps you can use tf2 or Keras version model to do the same process of CoreML.
